blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/elementmerc/anya/discussions
    about: For general questions or community chat
  - name: 📚 Documentation
    url: https://github.com/elementmerc/anya#readme
    about: Check the README and guides first